### Pytorch로 Softmax Regression 구현

In [15]:
# 학습 데이터 생성
import torch

x_train = torch.FloatTensor([[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]])
y_train = torch.FloatTensor([[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]])

In [16]:
# W, b 초기화
W = torch.zeros(4, 3, requires_grad=True)
b = torch.zeros(1, 3, requires_grad=True)

# Optimizer 생성
optimizer = torch.optim.Adam([W, b], lr=0.1)

In [17]:
# 반복횟수 설정
for epoch in range(3001):
  # 가설 및 비용 설정
  hypothesis = torch.softmax(torch.mm(x_train, W) + b, dim=1)
  cost = -torch.mean(torch.sum(y_train * torch.log(hypothesis), dim=1))
  # hypothesis = (torch.mm(x_train, W) + b).softmax(dim=1)
  # cost = -(y_train * torch.log(hypothesis)).sum(dim=1).mean()

  # Optimizer를 이용한 경사 계산 및 W, b 업데이트
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  # 학습이 잘 되는지 확인하기 위한 내용 출력
  if epoch % 300 == 0:
    print(f'epoch: {epoch}, cost: {cost.item():.6f}')

epoch: 0, cost: 1.098612
epoch: 300, cost: 0.105262
epoch: 600, cost: 0.042634
epoch: 900, cost: 0.023111
epoch: 1200, cost: 0.014479
epoch: 1500, cost: 0.009879
epoch: 1800, cost: 0.007124
epoch: 2100, cost: 0.005338
epoch: 2400, cost: 0.004113
epoch: 2700, cost: 0.003236
epoch: 3000, cost: 0.002588


In [18]:
# x가 [1, 11, 10, 9], [1, 3, 4, 3], [1, 1, 0, 1]일 때, y값은?
W.requires_grad_(False)
b.requires_grad_(False)

x_test = torch.FloatTensor([[1, 11, 10, 9], [1, 3, 4, 3], [1, 1, 0, 1]])
test_all = torch.softmax(torch.mm(x_test, W) + b, dim=1)
print(test_all)
print(torch.argmax(test_all, dim=1))

tensor([[1.0000e+00, 5.5165e-19, 7.0151e-38],
        [1.4800e-02, 7.4294e-01, 2.4226e-01],
        [1.2256e-33, 9.0835e-12, 1.0000e+00]])
tensor([0, 1, 2])


### 조금 더 깔끔하게 Softmax

In [19]:
import torch.nn.functional as F

# y_train 수정
y_train = torch.LongTensor([2, 2, 2, 1, 1, 1, 0, 0])

In [20]:
import torch.nn as nn

# W와 b를 n.Linear로 대체
model = nn.Linear(4, 3)
optimizer = torch.optim.Adam(model.parameters(), lr=1)

In [21]:
for epoch in range(3001):
  # 가설, 비용 수정
  # hypothesis = torch.softmax(torch.mm(x_train, W) + b, dim=1)
  # cost = -torch.mean(torch.sum(y_train * torch.log(hypothesis), dim=1))
  z = model(x_train)
  cost = F.cross_entropy(z, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 300 == 0:
    print(f'epoch: {epoch}, cost: {cost.item():.6f}')

epoch: 0, cost: 2.104534
epoch: 300, cost: 0.027749
epoch: 600, cost: 0.010477
epoch: 900, cost: 0.005577
epoch: 1200, cost: 0.003478
epoch: 1500, cost: 0.002371
epoch: 1800, cost: 0.001710
epoch: 2100, cost: 0.001282
epoch: 2400, cost: 0.000989
epoch: 2700, cost: 0.000779
epoch: 3000, cost: 0.000623


### Softmax Regression with Sklearn

In [24]:
import numpy as np
from sklearn.linear_model import LogisticRegression

x_train = np.array([[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]])

# y에 0, 1, 2 등 둘 이상의 class가 존재하기 때문에 softmax regression
y_train = np.array([2, 2, 2, 1, 1, 1, 0, 0])

logistic = LogisticRegression() # 모델 생성
logistic.fit(x_train, y_train) # 학습

pred = logistic.predict([[1, 11, 10, 9], [1, 3, 4, 3], [1, 1, 0, 1]]) # 값 예측
print(pred) # 출력

[0 2 2]
