## I. Numpy 시작하기  

### Remind : 리스트

In [1]:
arr = [1, "two", 3.0]

print(arr)

[1, 'two', 3.0]


### numpy 모듈 불러오기

In [2]:
import numpy as np

### 왜 numpy를 사용해야 할까요?

**List**

In [3]:
L = range(1000)

%timeit [i**2 for i in L]

232 µs ± 10.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


**numpy.array**

In [4]:
N = np.arange(1000)

%timeit N**2

1.12 µs ± 37.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### numpy.array

numpy의 Container, array

In [5]:
arr = np.array([1, 2, 3])

arr

array([1, 2, 3])

In [6]:
arr_2d = np.array([[1, 2 ,3], [4, 5, 6], [7, 8, 9]])

arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr.shape

(3,)

In [8]:
arr_2d.shape

(3, 3)

## II. Numpy로 연산하기

### Vertor와 Scalar 사이의 연산

벡터의 각 원소에 대해서 연산을 진행

In [9]:
x = np.array([1, 2, 3])
c = 5

print(f"더하기 : {x + c}")
print(f"빼기 : {x - c}")
print(f"곱하기 : {x * c}")
print(f"나누기 : {x / c}")

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


### Vertor와 Vertor 사이의 연산

벡터의 **같은 인덱스**끼리 연산을 진행

In [10]:
y = np.array([1, 3, 5])
z = np.array([2, 9, 20])

print(f"더하기 : {y + z}")
print(f"빼기 : {y - z}")
print(f"곱하기 : {y * z}")
print(f"나누기 : {y / z}")

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


### Array Indexing

python의 리스트와 유사하게 진행

In [11]:
w = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

w[0, 0]

1

In [12]:
w[2, 3]

12

In [13]:
w[1, 2]

7

### Array Slicing

python의 리스트와 유사하게 진행

In [14]:
w = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

w[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [15]:
w[0:2, 0:4]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
w[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
w[0:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
w[0:3, 2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [19]:
w[:, 2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

### Array의 Broadcasting

기본적으로 같은 Type의 data에 대해서만 연산이 적용 가능  
하지만 만약에 피연산자가 연산 가능하도록 변환이 가능하다면 연산이 가능합니다. 
이를 **Broadcasting**이라고 합니다.

### 1. M by N, M by 1

In [20]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([0, 1, 0])

x = x[:, None] # x를 전치
print(a+x)

[[1 2 3]
 [5 6 7]
 [7 8 9]]


### 2. M by N, 1 by N

In [21]:
y = np.array([0, 1, -1])

print(a * y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


### 3. M by 1, 1 by N

In [22]:
t = np.array([1, 2, 3])
t = t[:, None]

u = np.array([2, 0, -2])

print(t + u)

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


## Ⅲ. Numpy로 선형대수 지식 끼얹기

### A. basics

### 영벡터(행렬)
- 원소가 모두 0인 벡터(행렬)
- `np.zeros(dim)`을 통해 생성, dim은 값, 혹은 튜플(, )

In [23]:
np.zeros(3)

array([0., 0., 0.])

In [24]:
np.zeros((3, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### 일행렬

- 원소가 모두 1인 벡터(행렬)
- `np.ones(dim)`을 통해 생성, dim은 값, 혹은 튜플(, )

In [25]:
np.ones(2)

array([1., 1.])

In [26]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 대각행렬
- Main Diagonal을 제외한 성분이 0인 행렬
- `np.diag((main_diagonals))`을 통해 생성할 수 있음.

In [27]:
np.diag((2, 4))

array([[2, 0],
       [0, 4]])

In [28]:
np.diag((1, 3, 5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

### 항등행렬
- Main diagonal이 1이 대각행렬
- `np.eye(n, (dtype=int, uint, float, complex, ...))`를 사용

In [29]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 행렬곱
- 행렬간에 정의되는 곱 연산(dot product)
- `np.dot()`, @를 사용

In [31]:
mat_1 = np.array([[1, 4], [2, 3]])
mat_2 = np.array([[7, 9], [0, 6]])

mat_1.dot(mat_2)

array([[ 7, 33],
       [14, 36]])

In [32]:
mat_1 @ mat_2

array([[ 7, 33],
       [14, 36]])

### B. Furthermore

### 트레이스
- Main Diagonal의 합
- `np.trace()`를 사용

In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr.trace()

15

In [35]:
np.eye(2, dtype=int).trace()

2

### 행렬식
- 행렬을 대표하는 값들 중 하나
- 선형변환 과정에서 Vector의 Scaling 척도
- `np.linalg.det()`으로 계산

In [36]:
arr_2 = np.array([[2, 3], [1, 6]])

arr_2

array([[2, 3],
       [1, 6]])

In [37]:
np.linalg.det(arr_2)

9.000000000000002

In [38]:
arr_3 = np.array([[1, 4, 7], [2, 5, 8], [3, 6, 9]])

arr_3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [39]:
np.linalg.det(arr_3)

0.0

### 역행렬
- 행렬 A에 대해 AB = BA = I를 만족하는 행렬 B = A^-1
- `np.linalg.inv()`로 계산

In [40]:
mat = np.array([[1, 4], [2, 3]])

mat

array([[1, 4],
       [2, 3]])

In [41]:
mat_inv = np.linalg.inv(mat)

mat_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [42]:
mat @ mat_inv

array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00]])

### 고유값과 고유벡터
- 정방행렬(nxn) A에 대해서 $Ax = \lambda x$을 만족하는 $\lambda$와 x를 각각 고유값과 고유벡터라고 한다.
- np.linalg.eig()로 계산

In [43]:
mat = np.array([[2, 0, -2], [1, 1, -2], [0, 0, 1]])

mat

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [44]:
np.linalg.eig(mat)

(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

#### Validation

In [45]:
eig_val, eig_vec = np.linalg.eig(mat)

eig_val

array([1., 2., 1.])

In [46]:
eig_vec

array([[0.        , 0.70710678, 0.89442719],
       [1.        , 0.70710678, 0.        ],
       [0.        , 0.        , 0.4472136 ]])

In [47]:
mat @ eig_vec[:, 0] # Ax

array([0., 1., 0.])

In [48]:
eig_val[0] * eig_vec[:, 0] # (lambda)x

array([0., 1., 0.])

## IV. Exercises

#### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요
- 매개변수 : 1차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [1]:
def get_L2_norm(array):
    return np.linalg.norm(array)

#### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()`를 작성하세요
- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환

In [2]:
def is_singular(array):
    return np.linalg.det(array) == 0